/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['io.kubernetes.js/ApiClient', 'io.kubernetes.js/io.kubernetes.js.models/V1ObjectMeta', 'io.kubernetes.js/io.kubernetes.js.models/V1alpha1CertificateSigningRequestSpec', 'io.kubernetes.js/io.kubernetes.js.models/V1alpha1CertificateSigningRequestStatus'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./V1ObjectMeta'), require('./V1alpha1CertificateSigningRequestSpec'), require('./V1alpha1CertificateSigningRequestStatus'));
  } else {
    // Browser globals (root is window)
    if (!root.KubernetesJsClient) {
      root.KubernetesJsClient = {};
    }
    root.KubernetesJsClient.V1alpha1CertificateSigningRequest = factory(root.KubernetesJsClient.ApiClient, root.KubernetesJsClient.V1ObjectMeta, root.KubernetesJsClient.V1alpha1CertificateSigningRequestSpec, root.KubernetesJsClient.V1alpha1CertificateSigningRequestStatus);
  }
}(this, function(ApiClient, V1ObjectMeta, V1alpha1CertificateSigningRequestSpec, V1alpha1CertificateSigningRequestStatus) {
  'use strict';




  /**
   * The V1alpha1CertificateSigningRequest model module.
   * @module io.kubernetes.js/io.kubernetes.js.models/V1alpha1CertificateSigningRequest
   * @version 1.0-snapshot
   */

  /**
   * Constructs a new <code>V1alpha1CertificateSigningRequest</code>.
   * Describes a certificate signing request
   * @alias module:io.kubernetes.js/io.kubernetes.js.models/V1alpha1CertificateSigningRequest
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>V1alpha1CertificateSigningRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:io.kubernetes.js/io.kubernetes.js.models/V1alpha1CertificateSigningRequest} obj Optional instance to populate.
   * @return {module:io.kubernetes.js/io.kubernetes.js.models/V1alpha1CertificateSigningRequest} The populated <code>V1alpha1CertificateSigningRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('apiVersion')) {
        obj['apiVersion'] = ApiClient.convertToType(data['apiVersion'], 'String');
      }
      if (data.hasOwnProperty('kind')) {
        obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
      }
      if (data.hasOwnProperty('metadata')) {
        obj['metadata'] = V1ObjectMeta.constructFromObject(data['metadata']);
      }
      if (data.hasOwnProperty('spec')) {
        obj['spec'] = V1alpha1CertificateSigningRequestSpec.constructFromObject(data['spec']);
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = V1alpha1CertificateSigningRequestStatus.constructFromObject(data['status']);
      }
    }
    return obj;
  }

  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
   * @member {String} apiVersion
   */
  exports.prototype['apiVersion'] = undefined;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
   * @member {String} kind
   */
  exports.prototype['kind'] = undefined;
  /**
   * @member {module:io.kubernetes.js/io.kubernetes.js.models/V1ObjectMeta} metadata
   */
  exports.prototype['metadata'] = undefined;
  /**
   * The certificate request itself and any additional information.
   * @member {module:io.kubernetes.js/io.kubernetes.js.models/V1alpha1CertificateSigningRequestSpec} spec
   */
  exports.prototype['spec'] = undefined;
  /**
   * Derived information about the request.
   * @member {module:io.kubernetes.js/io.kubernetes.js.models/V1alpha1CertificateSigningRequestStatus} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


