/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['io.kubernetes.js/ApiClient', 'io.kubernetes.js/io.kubernetes.js.models/V1beta1CPUTargetUtilization', 'io.kubernetes.js/io.kubernetes.js.models/V1beta1SubresourceReference'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./V1beta1CPUTargetUtilization'), require('./V1beta1SubresourceReference'));
  } else {
    // Browser globals (root is window)
    if (!root.KubernetesJsClient) {
      root.KubernetesJsClient = {};
    }
    root.KubernetesJsClient.V1beta1HorizontalPodAutoscalerSpec = factory(root.KubernetesJsClient.ApiClient, root.KubernetesJsClient.V1beta1CPUTargetUtilization, root.KubernetesJsClient.V1beta1SubresourceReference);
  }
}(this, function(ApiClient, V1beta1CPUTargetUtilization, V1beta1SubresourceReference) {
  'use strict';




  /**
   * The V1beta1HorizontalPodAutoscalerSpec model module.
   * @module io.kubernetes.js/io.kubernetes.js.models/V1beta1HorizontalPodAutoscalerSpec
   * @version 1.0-snapshot
   */

  /**
   * Constructs a new <code>V1beta1HorizontalPodAutoscalerSpec</code>.
   * specification of a horizontal pod autoscaler.
   * @alias module:io.kubernetes.js/io.kubernetes.js.models/V1beta1HorizontalPodAutoscalerSpec
   * @class
   * @param maxReplicas {Number} upper limit for the number of pods that can be set by the autoscaler; cannot be smaller than MinReplicas.
   * @param scaleRef {module:io.kubernetes.js/io.kubernetes.js.models/V1beta1SubresourceReference} reference to Scale subresource; horizontal pod autoscaler will learn the current resource consumption from its status, and will set the desired number of pods by modifying its spec.
   */
  var exports = function(maxReplicas, scaleRef) {
    var _this = this;


    _this['maxReplicas'] = maxReplicas;

    _this['scaleRef'] = scaleRef;
  };

  /**
   * Constructs a <code>V1beta1HorizontalPodAutoscalerSpec</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:io.kubernetes.js/io.kubernetes.js.models/V1beta1HorizontalPodAutoscalerSpec} obj Optional instance to populate.
   * @return {module:io.kubernetes.js/io.kubernetes.js.models/V1beta1HorizontalPodAutoscalerSpec} The populated <code>V1beta1HorizontalPodAutoscalerSpec</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('cpuUtilization')) {
        obj['cpuUtilization'] = V1beta1CPUTargetUtilization.constructFromObject(data['cpuUtilization']);
      }
      if (data.hasOwnProperty('maxReplicas')) {
        obj['maxReplicas'] = ApiClient.convertToType(data['maxReplicas'], 'Number');
      }
      if (data.hasOwnProperty('minReplicas')) {
        obj['minReplicas'] = ApiClient.convertToType(data['minReplicas'], 'Number');
      }
      if (data.hasOwnProperty('scaleRef')) {
        obj['scaleRef'] = V1beta1SubresourceReference.constructFromObject(data['scaleRef']);
      }
    }
    return obj;
  }

  /**
   * target average CPU utilization (represented as a percentage of requested CPU) over all the pods; if not specified it defaults to the target CPU utilization at 80% of the requested resources.
   * @member {module:io.kubernetes.js/io.kubernetes.js.models/V1beta1CPUTargetUtilization} cpuUtilization
   */
  exports.prototype['cpuUtilization'] = undefined;
  /**
   * upper limit for the number of pods that can be set by the autoscaler; cannot be smaller than MinReplicas.
   * @member {Number} maxReplicas
   */
  exports.prototype['maxReplicas'] = undefined;
  /**
   * lower limit for the number of pods that can be set by the autoscaler, default 1.
   * @member {Number} minReplicas
   */
  exports.prototype['minReplicas'] = undefined;
  /**
   * reference to Scale subresource; horizontal pod autoscaler will learn the current resource consumption from its status, and will set the desired number of pods by modifying its spec.
   * @member {module:io.kubernetes.js/io.kubernetes.js.models/V1beta1SubresourceReference} scaleRef
   */
  exports.prototype['scaleRef'] = undefined;



  return exports;
}));


