/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.5.1-660c2a2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['io.kubernetes.js/ApiClient', 'io.kubernetes.js/io.kubernetes.js.models/IntstrIntOrString'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./IntstrIntOrString'));
  } else {
    // Browser globals (root is window)
    if (!root.KubernetesJsClient) {
      root.KubernetesJsClient = {};
    }
    root.KubernetesJsClient.V1TCPSocketAction = factory(root.KubernetesJsClient.ApiClient, root.KubernetesJsClient.IntstrIntOrString);
  }
}(this, function(ApiClient, IntstrIntOrString) {
  'use strict';




  /**
   * The V1TCPSocketAction model module.
   * @module io.kubernetes.js/io.kubernetes.js.models/V1TCPSocketAction
   * @version 1.0-snapshot
   */

  /**
   * Constructs a new <code>V1TCPSocketAction</code>.
   * TCPSocketAction describes an action based on opening a socket
   * @alias module:io.kubernetes.js/io.kubernetes.js.models/V1TCPSocketAction
   * @class
   * @param port {module:io.kubernetes.js/io.kubernetes.js.models/IntstrIntOrString} Number or name of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
   */
  var exports = function(port) {
    var _this = this;

    _this['port'] = port;
  };

  /**
   * Constructs a <code>V1TCPSocketAction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:io.kubernetes.js/io.kubernetes.js.models/V1TCPSocketAction} obj Optional instance to populate.
   * @return {module:io.kubernetes.js/io.kubernetes.js.models/V1TCPSocketAction} The populated <code>V1TCPSocketAction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('port')) {
        obj['port'] = IntstrIntOrString.constructFromObject(data['port']);
      }
    }
    return obj;
  }

  /**
   * Number or name of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
   * @member {module:io.kubernetes.js/io.kubernetes.js.models/IntstrIntOrString} port
   */
  exports.prototype['port'] = undefined;



  return exports;
}));


