/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UnversionedServerAddressByClientCIDR'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UnversionedServerAddressByClientCIDR'));
  } else {
    // Browser globals (root is window)
    if (!root.Kubernetes) {
      root.Kubernetes = {};
    }
    root.Kubernetes.UnversionedAPIVersions = factory(root.Kubernetes.ApiClient, root.Kubernetes.UnversionedServerAddressByClientCIDR);
  }
}(this, function(ApiClient, UnversionedServerAddressByClientCIDR) {
  'use strict';




  /**
   * The UnversionedAPIVersions model module.
   * @module model/UnversionedAPIVersions
   * @version unversioned
   */

  /**
   * Constructs a new <code>UnversionedAPIVersions</code>.
   * APIVersions lists the versions that are available, to allow clients to discover the API at /api, which is the root path of the legacy v1 API.
   * @alias module:model/UnversionedAPIVersions
   * @class
   * @param serverAddressByClientCIDRs {Array.<module:model/UnversionedServerAddressByClientCIDR>} a map of client CIDR to server address that is serving this group. This is to help clients reach servers in the most network-efficient way possible. Clients can use the appropriate server address as per the CIDR that they match. In case of multiple matches, clients should use the longest matching CIDR. The server returns only those CIDRs that it thinks that the client can match. For example: the master will return an internal IP CIDR only, if the client reaches the server using an internal IP. Server looks at X-Forwarded-For header or X-Real-Ip header or request.RemoteAddr (in that order) to get the client IP.
   * @param versions {Array.<String>} versions are the api versions that are available.
   */
  var exports = function(serverAddressByClientCIDRs, versions) {
    var _this = this;



    _this['serverAddressByClientCIDRs'] = serverAddressByClientCIDRs;
    _this['versions'] = versions;
  };

  /**
   * Constructs a <code>UnversionedAPIVersions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnversionedAPIVersions} obj Optional instance to populate.
   * @return {module:model/UnversionedAPIVersions} The populated <code>UnversionedAPIVersions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('apiVersion')) {
        obj['apiVersion'] = ApiClient.convertToType(data['apiVersion'], 'String');
      }
      if (data.hasOwnProperty('kind')) {
        obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
      }
      if (data.hasOwnProperty('serverAddressByClientCIDRs')) {
        obj['serverAddressByClientCIDRs'] = ApiClient.convertToType(data['serverAddressByClientCIDRs'], [UnversionedServerAddressByClientCIDR]);
      }
      if (data.hasOwnProperty('versions')) {
        obj['versions'] = ApiClient.convertToType(data['versions'], ['String']);
      }
    }
    return obj;
  }

  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
   * @member {String} apiVersion
   */
  exports.prototype['apiVersion'] = undefined;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
   * @member {String} kind
   */
  exports.prototype['kind'] = undefined;
  /**
   * a map of client CIDR to server address that is serving this group. This is to help clients reach servers in the most network-efficient way possible. Clients can use the appropriate server address as per the CIDR that they match. In case of multiple matches, clients should use the longest matching CIDR. The server returns only those CIDRs that it thinks that the client can match. For example: the master will return an internal IP CIDR only, if the client reaches the server using an internal IP. Server looks at X-Forwarded-For header or X-Real-Ip header or request.RemoteAddr (in that order) to get the client IP.
   * @member {Array.<module:model/UnversionedServerAddressByClientCIDR>} serverAddressByClientCIDRs
   */
  exports.prototype['serverAddressByClientCIDRs'] = undefined;
  /**
   * versions are the api versions that are available.
   * @member {Array.<String>} versions
   */
  exports.prototype['versions'] = undefined;



  return exports;
}));


