/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UnversionedAPIResource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UnversionedAPIResource'));
  } else {
    // Browser globals (root is window)
    if (!root.Kubernetes) {
      root.Kubernetes = {};
    }
    root.Kubernetes.UnversionedAPIResourceList = factory(root.Kubernetes.ApiClient, root.Kubernetes.UnversionedAPIResource);
  }
}(this, function(ApiClient, UnversionedAPIResource) {
  'use strict';




  /**
   * The UnversionedAPIResourceList model module.
   * @module model/UnversionedAPIResourceList
   * @version unversioned
   */

  /**
   * Constructs a new <code>UnversionedAPIResourceList</code>.
   * APIResourceList is a list of APIResource, it is used to expose the name of the resources supported in a specific group and version, and if the resource is namespaced.
   * @alias module:model/UnversionedAPIResourceList
   * @class
   * @param groupVersion {String} groupVersion is the group and version this APIResourceList is for.
   * @param resources {Array.<module:model/UnversionedAPIResource>} resources contains the name of the resources and if they are namespaced.
   */
  var exports = function(groupVersion, resources) {
    var _this = this;


    _this['groupVersion'] = groupVersion;

    _this['resources'] = resources;
  };

  /**
   * Constructs a <code>UnversionedAPIResourceList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnversionedAPIResourceList} obj Optional instance to populate.
   * @return {module:model/UnversionedAPIResourceList} The populated <code>UnversionedAPIResourceList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('apiVersion')) {
        obj['apiVersion'] = ApiClient.convertToType(data['apiVersion'], 'String');
      }
      if (data.hasOwnProperty('groupVersion')) {
        obj['groupVersion'] = ApiClient.convertToType(data['groupVersion'], 'String');
      }
      if (data.hasOwnProperty('kind')) {
        obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
      }
      if (data.hasOwnProperty('resources')) {
        obj['resources'] = ApiClient.convertToType(data['resources'], [UnversionedAPIResource]);
      }
    }
    return obj;
  }

  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources
   * @member {String} apiVersion
   */
  exports.prototype['apiVersion'] = undefined;
  /**
   * groupVersion is the group and version this APIResourceList is for.
   * @member {String} groupVersion
   */
  exports.prototype['groupVersion'] = undefined;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
   * @member {String} kind
   */
  exports.prototype['kind'] = undefined;
  /**
   * resources contains the name of the resources and if they are namespaced.
   * @member {Array.<module:model/UnversionedAPIResource>} resources
   */
  exports.prototype['resources'] = undefined;



  return exports;
}));


