/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UnversionedLabelSelectorRequirement'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UnversionedLabelSelectorRequirement'));
  } else {
    // Browser globals (root is window)
    if (!root.Kubernetes) {
      root.Kubernetes = {};
    }
    root.Kubernetes.UnversionedLabelSelector = factory(root.Kubernetes.ApiClient, root.Kubernetes.UnversionedLabelSelectorRequirement);
  }
}(this, function(ApiClient, UnversionedLabelSelectorRequirement) {
  'use strict';




  /**
   * The UnversionedLabelSelector model module.
   * @module model/UnversionedLabelSelector
   * @version unversioned
   */

  /**
   * Constructs a new <code>UnversionedLabelSelector</code>.
   * A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
   * @alias module:model/UnversionedLabelSelector
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>UnversionedLabelSelector</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnversionedLabelSelector} obj Optional instance to populate.
   * @return {module:model/UnversionedLabelSelector} The populated <code>UnversionedLabelSelector</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('matchExpressions')) {
        obj['matchExpressions'] = ApiClient.convertToType(data['matchExpressions'], [UnversionedLabelSelectorRequirement]);
      }
      if (data.hasOwnProperty('matchLabels')) {
        obj['matchLabels'] = ApiClient.convertToType(data['matchLabels'], {'String': 'String'});
      }
    }
    return obj;
  }

  /**
   * matchExpressions is a list of label selector requirements. The requirements are ANDed.
   * @member {Array.<module:model/UnversionedLabelSelectorRequirement>} matchExpressions
   */
  exports.prototype['matchExpressions'] = undefined;
  /**
   * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed.
   * @member {Object.<String, String>} matchLabels
   */
  exports.prototype['matchLabels'] = undefined;



  return exports;
}));


