/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/V1beta1NonResourceAttributes', 'model/V1beta1ResourceAttributes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./V1beta1NonResourceAttributes'), require('./V1beta1ResourceAttributes'));
  } else {
    // Browser globals (root is window)
    if (!root.Kubernetes) {
      root.Kubernetes = {};
    }
    root.Kubernetes.V1beta1SelfSubjectAccessReviewSpec = factory(root.Kubernetes.ApiClient, root.Kubernetes.V1beta1NonResourceAttributes, root.Kubernetes.V1beta1ResourceAttributes);
  }
}(this, function(ApiClient, V1beta1NonResourceAttributes, V1beta1ResourceAttributes) {
  'use strict';




  /**
   * The V1beta1SelfSubjectAccessReviewSpec model module.
   * @module model/V1beta1SelfSubjectAccessReviewSpec
   * @version unversioned
   */

  /**
   * Constructs a new <code>V1beta1SelfSubjectAccessReviewSpec</code>.
   * SelfSubjectAccessReviewSpec is a description of the access request.  Exactly one of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes must be set
   * @alias module:model/V1beta1SelfSubjectAccessReviewSpec
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>V1beta1SelfSubjectAccessReviewSpec</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1beta1SelfSubjectAccessReviewSpec} obj Optional instance to populate.
   * @return {module:model/V1beta1SelfSubjectAccessReviewSpec} The populated <code>V1beta1SelfSubjectAccessReviewSpec</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('nonResourceAttributes')) {
        obj['nonResourceAttributes'] = V1beta1NonResourceAttributes.constructFromObject(data['nonResourceAttributes']);
      }
      if (data.hasOwnProperty('resourceAttributes')) {
        obj['resourceAttributes'] = V1beta1ResourceAttributes.constructFromObject(data['resourceAttributes']);
      }
    }
    return obj;
  }

  /**
   * NonResourceAttributes describes information for a non-resource access request
   * @member {module:model/V1beta1NonResourceAttributes} nonResourceAttributes
   */
  exports.prototype['nonResourceAttributes'] = undefined;
  /**
   * ResourceAuthorizationAttributes describes information for a resource access request
   * @member {module:model/V1beta1ResourceAttributes} resourceAttributes
   */
  exports.prototype['resourceAttributes'] = undefined;



  return exports;
}));


