/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/V1beta1UserInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./V1beta1UserInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.Kubernetes) {
      root.Kubernetes = {};
    }
    root.Kubernetes.V1beta1TokenReviewStatus = factory(root.Kubernetes.ApiClient, root.Kubernetes.V1beta1UserInfo);
  }
}(this, function(ApiClient, V1beta1UserInfo) {
  'use strict';




  /**
   * The V1beta1TokenReviewStatus model module.
   * @module model/V1beta1TokenReviewStatus
   * @version v1.6.0
   */

  /**
   * Constructs a new <code>V1beta1TokenReviewStatus</code>.
   * TokenReviewStatus is the result of the token authentication request.
   * @alias module:model/V1beta1TokenReviewStatus
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>V1beta1TokenReviewStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1beta1TokenReviewStatus} obj Optional instance to populate.
   * @return {module:model/V1beta1TokenReviewStatus} The populated <code>V1beta1TokenReviewStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('authenticated')) {
        obj['authenticated'] = ApiClient.convertToType(data['authenticated'], 'Boolean');
      }
      if (data.hasOwnProperty('error')) {
        obj['error'] = ApiClient.convertToType(data['error'], 'String');
      }
      if (data.hasOwnProperty('user')) {
        obj['user'] = V1beta1UserInfo.constructFromObject(data['user']);
      }
    }
    return obj;
  }

  /**
   * Authenticated indicates that the token was associated with a known user.
   * @member {Boolean} authenticated
   */
  exports.prototype['authenticated'] = undefined;
  /**
   * Error indicates that the token couldn't be checked
   * @member {String} error
   */
  exports.prototype['error'] = undefined;
  /**
   * User is the UserInfo associated with the provided token.
   * @member {module:model/V1beta1UserInfo} user
   */
  exports.prototype['user'] = undefined;



  return exports;
}));


