/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/IntstrIntOrString'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./IntstrIntOrString'));
  } else {
    // Browser globals (root is window)
    if (!root.Kubernetes) {
      root.Kubernetes = {};
    }
    root.Kubernetes.V1beta1NetworkPolicyPort = factory(root.Kubernetes.ApiClient, root.Kubernetes.IntstrIntOrString);
  }
}(this, function(ApiClient, IntstrIntOrString) {
  'use strict';




  /**
   * The V1beta1NetworkPolicyPort model module.
   * @module model/V1beta1NetworkPolicyPort
   * @version v1.6.0
   */

  /**
   * Constructs a new <code>V1beta1NetworkPolicyPort</code>.
   * @alias module:model/V1beta1NetworkPolicyPort
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>V1beta1NetworkPolicyPort</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1beta1NetworkPolicyPort} obj Optional instance to populate.
   * @return {module:model/V1beta1NetworkPolicyPort} The populated <code>V1beta1NetworkPolicyPort</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('port')) {
        obj['port'] = IntstrIntOrString.constructFromObject(data['port']);
      }
      if (data.hasOwnProperty('protocol')) {
        obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
      }
    }
    return obj;
  }

  /**
   * If specified, the port on the given protocol.  This can either be a numerical or named port on a pod.  If this field is not provided, this matches all port names and numbers. If present, only traffic on the specified protocol AND port will be matched.
   * @member {module:model/IntstrIntOrString} port
   */
  exports.prototype['port'] = undefined;
  /**
   * Optional.  The protocol (TCP or UDP) which traffic must match. If not specified, this field defaults to TCP.
   * @member {String} protocol
   */
  exports.prototype['protocol'] = undefined;



  return exports;
}));


