/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Kubernetes) {
      root.Kubernetes = {};
    }
    root.Kubernetes.V1ContainerPort = factory(root.Kubernetes.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The V1ContainerPort model module.
   * @module model/V1ContainerPort
   * @version unversioned
   */

  /**
   * Constructs a new <code>V1ContainerPort</code>.
   * ContainerPort represents a network port in a single container.
   * @alias module:model/V1ContainerPort
   * @class
   * @param containerPort {Integer} Number of port to expose on the pod's IP address. This must be a valid port number, 0 < x < 65536.
   */
  var exports = function(containerPort) {
    var _this = this;

    _this['containerPort'] = containerPort;




  };

  /**
   * Constructs a <code>V1ContainerPort</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1ContainerPort} obj Optional instance to populate.
   * @return {module:model/V1ContainerPort} The populated <code>V1ContainerPort</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('containerPort')) {
        obj['containerPort'] = ApiClient.convertToType(data['containerPort'], 'Integer');
      }
      if (data.hasOwnProperty('hostIP')) {
        obj['hostIP'] = ApiClient.convertToType(data['hostIP'], 'String');
      }
      if (data.hasOwnProperty('hostPort')) {
        obj['hostPort'] = ApiClient.convertToType(data['hostPort'], 'Integer');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('protocol')) {
        obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
      }
    }
    return obj;
  }

  /**
   * Number of port to expose on the pod's IP address. This must be a valid port number, 0 < x < 65536.
   * @member {Integer} containerPort
   */
  exports.prototype['containerPort'] = undefined;
  /**
   * What host IP to bind the external port to.
   * @member {String} hostIP
   */
  exports.prototype['hostIP'] = undefined;
  /**
   * Number of port to expose on the host. If specified, this must be a valid port number, 0 < x < 65536. If HostNetwork is specified, this must match ContainerPort. Most containers do not need this.
   * @member {Integer} hostPort
   */
  exports.prototype['hostPort'] = undefined;
  /**
   * If specified, this must be an IANA_SVC_NAME and unique within the pod. Each named port in a pod must have a unique name. Name for the port that can be referred to by services.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Protocol for port. Must be UDP or TCP. Defaults to \"TCP\".
   * @member {String} protocol
   */
  exports.prototype['protocol'] = undefined;



  return exports;
}));


