/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/V1ContainerStateRunning', 'model/V1ContainerStateTerminated', 'model/V1ContainerStateWaiting'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./V1ContainerStateRunning'), require('./V1ContainerStateTerminated'), require('./V1ContainerStateWaiting'));
  } else {
    // Browser globals (root is window)
    if (!root.Kubernetes) {
      root.Kubernetes = {};
    }
    root.Kubernetes.V1ContainerState = factory(root.Kubernetes.ApiClient, root.Kubernetes.V1ContainerStateRunning, root.Kubernetes.V1ContainerStateTerminated, root.Kubernetes.V1ContainerStateWaiting);
  }
}(this, function(ApiClient, V1ContainerStateRunning, V1ContainerStateTerminated, V1ContainerStateWaiting) {
  'use strict';




  /**
   * The V1ContainerState model module.
   * @module model/V1ContainerState
   * @version unversioned
   */

  /**
   * Constructs a new <code>V1ContainerState</code>.
   * ContainerState holds a possible state of container. Only one of its members may be specified. If none of them is specified, the default one is ContainerStateWaiting.
   * @alias module:model/V1ContainerState
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>V1ContainerState</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1ContainerState} obj Optional instance to populate.
   * @return {module:model/V1ContainerState} The populated <code>V1ContainerState</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('running')) {
        obj['running'] = V1ContainerStateRunning.constructFromObject(data['running']);
      }
      if (data.hasOwnProperty('terminated')) {
        obj['terminated'] = V1ContainerStateTerminated.constructFromObject(data['terminated']);
      }
      if (data.hasOwnProperty('waiting')) {
        obj['waiting'] = V1ContainerStateWaiting.constructFromObject(data['waiting']);
      }
    }
    return obj;
  }

  /**
   * Details about a running container
   * @member {module:model/V1ContainerStateRunning} running
   */
  exports.prototype['running'] = undefined;
  /**
   * Details about a terminated container
   * @member {module:model/V1ContainerStateTerminated} terminated
   */
  exports.prototype['terminated'] = undefined;
  /**
   * Details about a waiting container
   * @member {module:model/V1ContainerStateWaiting} waiting
   */
  exports.prototype['waiting'] = undefined;



  return exports;
}));


