/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/V1JobCondition', 'model/V1Time'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./V1JobCondition'), require('./V1Time'));
  } else {
    // Browser globals (root is window)
    if (!root.Kubernetes) {
      root.Kubernetes = {};
    }
    root.Kubernetes.V1JobStatus = factory(root.Kubernetes.ApiClient, root.Kubernetes.V1JobCondition, root.Kubernetes.V1Time);
  }
}(this, function(ApiClient, V1JobCondition, V1Time) {
  'use strict';




  /**
   * The V1JobStatus model module.
   * @module model/V1JobStatus
   * @version v1.6.0
   */

  /**
   * Constructs a new <code>V1JobStatus</code>.
   * JobStatus represents the current state of a Job.
   * @alias module:model/V1JobStatus
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>V1JobStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1JobStatus} obj Optional instance to populate.
   * @return {module:model/V1JobStatus} The populated <code>V1JobStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('active')) {
        obj['active'] = ApiClient.convertToType(data['active'], 'Integer');
      }
      if (data.hasOwnProperty('completionTime')) {
        obj['completionTime'] = V1Time.constructFromObject(data['completionTime']);
      }
      if (data.hasOwnProperty('conditions')) {
        obj['conditions'] = ApiClient.convertToType(data['conditions'], [V1JobCondition]);
      }
      if (data.hasOwnProperty('failed')) {
        obj['failed'] = ApiClient.convertToType(data['failed'], 'Integer');
      }
      if (data.hasOwnProperty('startTime')) {
        obj['startTime'] = V1Time.constructFromObject(data['startTime']);
      }
      if (data.hasOwnProperty('succeeded')) {
        obj['succeeded'] = ApiClient.convertToType(data['succeeded'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * Active is the number of actively running pods.
   * @member {Integer} active
   */
  exports.prototype['active'] = undefined;
  /**
   * CompletionTime represents time when the job was completed. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.
   * @member {module:model/V1Time} completionTime
   */
  exports.prototype['completionTime'] = undefined;
  /**
   * Conditions represent the latest available observations of an object's current state. More info: http://kubernetes.io/docs/user-guide/jobs
   * @member {Array.<module:model/V1JobCondition>} conditions
   */
  exports.prototype['conditions'] = undefined;
  /**
   * Failed is the number of pods which reached Phase Failed.
   * @member {Integer} failed
   */
  exports.prototype['failed'] = undefined;
  /**
   * StartTime represents time when the job was acknowledged by the Job Manager. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.
   * @member {module:model/V1Time} startTime
   */
  exports.prototype['startTime'] = undefined;
  /**
   * Succeeded is the number of pods which reached Phase Succeeded.
   * @member {Integer} succeeded
   */
  exports.prototype['succeeded'] = undefined;



  return exports;
}));


