/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/V1NodeSelectorRequirement'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./V1NodeSelectorRequirement'));
  } else {
    // Browser globals (root is window)
    if (!root.Kubernetes) {
      root.Kubernetes = {};
    }
    root.Kubernetes.V1NodeSelectorTerm = factory(root.Kubernetes.ApiClient, root.Kubernetes.V1NodeSelectorRequirement);
  }
}(this, function(ApiClient, V1NodeSelectorRequirement) {
  'use strict';




  /**
   * The V1NodeSelectorTerm model module.
   * @module model/V1NodeSelectorTerm
   * @version v1.6.0
   */

  /**
   * Constructs a new <code>V1NodeSelectorTerm</code>.
   * A null or empty node selector term matches no objects.
   * @alias module:model/V1NodeSelectorTerm
   * @class
   * @param matchExpressions {Array.<module:model/V1NodeSelectorRequirement>} Required. A list of node selector requirements. The requirements are ANDed.
   */
  var exports = function(matchExpressions) {
    var _this = this;

    _this['matchExpressions'] = matchExpressions;
  };

  /**
   * Constructs a <code>V1NodeSelectorTerm</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1NodeSelectorTerm} obj Optional instance to populate.
   * @return {module:model/V1NodeSelectorTerm} The populated <code>V1NodeSelectorTerm</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('matchExpressions')) {
        obj['matchExpressions'] = ApiClient.convertToType(data['matchExpressions'], [V1NodeSelectorRequirement]);
      }
    }
    return obj;
  }

  /**
   * Required. A list of node selector requirements. The requirements are ANDed.
   * @member {Array.<module:model/V1NodeSelectorRequirement>} matchExpressions
   */
  exports.prototype['matchExpressions'] = undefined;



  return exports;
}));


