/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Kubernetes) {
      root.Kubernetes = {};
    }
    root.Kubernetes.V1NodeSpec = factory(root.Kubernetes.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The V1NodeSpec model module.
   * @module model/V1NodeSpec
   * @version unversioned
   */

  /**
   * Constructs a new <code>V1NodeSpec</code>.
   * NodeSpec describes the attributes that a node is created with.
   * @alias module:model/V1NodeSpec
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>V1NodeSpec</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1NodeSpec} obj Optional instance to populate.
   * @return {module:model/V1NodeSpec} The populated <code>V1NodeSpec</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('externalID')) {
        obj['externalID'] = ApiClient.convertToType(data['externalID'], 'String');
      }
      if (data.hasOwnProperty('podCIDR')) {
        obj['podCIDR'] = ApiClient.convertToType(data['podCIDR'], 'String');
      }
      if (data.hasOwnProperty('providerID')) {
        obj['providerID'] = ApiClient.convertToType(data['providerID'], 'String');
      }
      if (data.hasOwnProperty('unschedulable')) {
        obj['unschedulable'] = ApiClient.convertToType(data['unschedulable'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * External ID of the node assigned by some machine database (e.g. a cloud provider). Deprecated.
   * @member {String} externalID
   */
  exports.prototype['externalID'] = undefined;
  /**
   * PodCIDR represents the pod IP range assigned to the node.
   * @member {String} podCIDR
   */
  exports.prototype['podCIDR'] = undefined;
  /**
   * ID of the node assigned by the cloud provider in the format: <ProviderName>://<ProviderSpecificNodeID>
   * @member {String} providerID
   */
  exports.prototype['providerID'] = undefined;
  /**
   * Unschedulable controls node schedulability of new pods. By default, node is schedulable. More info: http://releases.k8s.io/HEAD/docs/admin/node.md#manual-node-administration\"
   * @member {Boolean} unschedulable
   */
  exports.prototype['unschedulable'] = undefined;



  return exports;
}));


