/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Kubernetes) {
      root.Kubernetes = {};
    }
    root.Kubernetes.V1ScaleStatus = factory(root.Kubernetes.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The V1ScaleStatus model module.
   * @module model/V1ScaleStatus
   * @version v1.6.0
   */

  /**
   * Constructs a new <code>V1ScaleStatus</code>.
   * ScaleStatus represents the current status of a scale subresource.
   * @alias module:model/V1ScaleStatus
   * @class
   * @param replicas {Integer} actual number of observed instances of the scaled object.
   */
  var exports = function(replicas) {
    var _this = this;

    _this['replicas'] = replicas;

  };

  /**
   * Constructs a <code>V1ScaleStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1ScaleStatus} obj Optional instance to populate.
   * @return {module:model/V1ScaleStatus} The populated <code>V1ScaleStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('replicas')) {
        obj['replicas'] = ApiClient.convertToType(data['replicas'], 'Integer');
      }
      if (data.hasOwnProperty('selector')) {
        obj['selector'] = ApiClient.convertToType(data['selector'], 'String');
      }
    }
    return obj;
  }

  /**
   * actual number of observed instances of the scaled object.
   * @member {Integer} replicas
   */
  exports.prototype['replicas'] = undefined;
  /**
   * label query over pods that should match the replicas count. This is same as the label selector but in the string format to avoid introspection by clients. The string will be in the same format as the query-param syntax. More info about label selectors: http://kubernetes.io/docs/user-guide/labels#label-selectors
   * @member {String} selector
   */
  exports.prototype['selector'] = undefined;



  return exports;
}));


