/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/V1StatusCause'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./V1StatusCause'));
  } else {
    // Browser globals (root is window)
    if (!root.Kubernetes) {
      root.Kubernetes = {};
    }
    root.Kubernetes.V1StatusDetails = factory(root.Kubernetes.ApiClient, root.Kubernetes.V1StatusCause);
  }
}(this, function(ApiClient, V1StatusCause) {
  'use strict';




  /**
   * The V1StatusDetails model module.
   * @module model/V1StatusDetails
   * @version v1.6.0
   */

  /**
   * Constructs a new <code>V1StatusDetails</code>.
   * StatusDetails is a set of additional properties that MAY be set by the server to provide additional information about a response. The Reason field of a Status object defines what attributes will be set. Clients must ignore fields that do not match the defined type of each attribute, and should assume that any attribute may be empty, invalid, or under defined.
   * @alias module:model/V1StatusDetails
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>V1StatusDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1StatusDetails} obj Optional instance to populate.
   * @return {module:model/V1StatusDetails} The populated <code>V1StatusDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('causes')) {
        obj['causes'] = ApiClient.convertToType(data['causes'], [V1StatusCause]);
      }
      if (data.hasOwnProperty('group')) {
        obj['group'] = ApiClient.convertToType(data['group'], 'String');
      }
      if (data.hasOwnProperty('kind')) {
        obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('retryAfterSeconds')) {
        obj['retryAfterSeconds'] = ApiClient.convertToType(data['retryAfterSeconds'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * The Causes array includes more details associated with the StatusReason failure. Not all StatusReasons may provide detailed causes.
   * @member {Array.<module:model/V1StatusCause>} causes
   */
  exports.prototype['causes'] = undefined;
  /**
   * The group attribute of the resource associated with the status StatusReason.
   * @member {String} group
   */
  exports.prototype['group'] = undefined;
  /**
   * The kind attribute of the resource associated with the status StatusReason. On some operations may differ from the requested resource Kind. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
   * @member {String} kind
   */
  exports.prototype['kind'] = undefined;
  /**
   * The name attribute of the resource associated with the status StatusReason (when there is a single name which can be described).
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * If specified, the time in seconds before the operation should be retried.
   * @member {Integer} retryAfterSeconds
   */
  exports.prototype['retryAfterSeconds'] = undefined;



  return exports;
}));


