/**
 * Kubernetes
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Kubernetes);
  }
}(this, function(expect, Kubernetes) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Kubernetes.V1Volume();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('V1Volume', function() {
    it('should create an instance of V1Volume', function() {
      // uncomment below and update the code to test V1Volume
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be.a(Kubernetes.V1Volume);
    });

    it('should have the property awsElasticBlockStore (base name: "awsElasticBlockStore")', function() {
      // uncomment below and update the code to test the property awsElasticBlockStore
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property azureDisk (base name: "azureDisk")', function() {
      // uncomment below and update the code to test the property azureDisk
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property azureFile (base name: "azureFile")', function() {
      // uncomment below and update the code to test the property azureFile
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property cephfs (base name: "cephfs")', function() {
      // uncomment below and update the code to test the property cephfs
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property cinder (base name: "cinder")', function() {
      // uncomment below and update the code to test the property cinder
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property configMap (base name: "configMap")', function() {
      // uncomment below and update the code to test the property configMap
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property downwardAPI (base name: "downwardAPI")', function() {
      // uncomment below and update the code to test the property downwardAPI
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property emptyDir (base name: "emptyDir")', function() {
      // uncomment below and update the code to test the property emptyDir
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property fc (base name: "fc")', function() {
      // uncomment below and update the code to test the property fc
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property flexVolume (base name: "flexVolume")', function() {
      // uncomment below and update the code to test the property flexVolume
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property flocker (base name: "flocker")', function() {
      // uncomment below and update the code to test the property flocker
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property gcePersistentDisk (base name: "gcePersistentDisk")', function() {
      // uncomment below and update the code to test the property gcePersistentDisk
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property gitRepo (base name: "gitRepo")', function() {
      // uncomment below and update the code to test the property gitRepo
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property glusterfs (base name: "glusterfs")', function() {
      // uncomment below and update the code to test the property glusterfs
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property hostPath (base name: "hostPath")', function() {
      // uncomment below and update the code to test the property hostPath
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property iscsi (base name: "iscsi")', function() {
      // uncomment below and update the code to test the property iscsi
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property nfs (base name: "nfs")', function() {
      // uncomment below and update the code to test the property nfs
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property persistentVolumeClaim (base name: "persistentVolumeClaim")', function() {
      // uncomment below and update the code to test the property persistentVolumeClaim
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property photonPersistentDisk (base name: "photonPersistentDisk")', function() {
      // uncomment below and update the code to test the property photonPersistentDisk
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property quobyte (base name: "quobyte")', function() {
      // uncomment below and update the code to test the property quobyte
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property rbd (base name: "rbd")', function() {
      // uncomment below and update the code to test the property rbd
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property secret (base name: "secret")', function() {
      // uncomment below and update the code to test the property secret
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

    it('should have the property vsphereVolume (base name: "vsphereVolume")', function() {
      // uncomment below and update the code to test the property vsphereVolume
      //var instane = new Kubernetes.V1Volume();
      //expect(instance).to.be();
    });

  });

}));
